Repository evergage/evergage-global-templates, pull requests merged in 2020-09, with the labels that each got.

#17 EVG-12453 | Exit Intent Popup Link Fix
  exit-intent-email-capture/template.hbs
  exit-intent-popup/template.hbs
Labels: Bug, Release Requested, Security

#18 EVG-12008: Remove contentZone from Serverside code
  README.md
  exit-intent-popup-email-capture/client.js
  exit-intent-popup-email-capture/evergage-template.json
  exit-intent-popup-email-capture/template.css
  exit-intent-popup-email-capture/template.hbs
  exit-intent-popup-email-capture/template.png
  exit-intent-popup-email-capture/template.ts
  exit-intent-popup/client.js
  exit-intent-popup/template.css
  exit-intent-popup/template.ts
  recipe-content-recommendations/template.ts
  recipe-product-recommendations/template.ts
Labels: Release Requested

#19 EVG-11976: Global Template | [V2] Hero Banner with Call-To-Action
  README.md
  hero-banner-cta/client.js
  hero-banner-cta/config.png
  hero-banner-cta/template.css
  hero-banner-cta/template.hbs
  hero-banner-cta/template.png
  hero-banner-cta/template.ts
Labels: Release Requested, Security

#14 EVG-12051 | Infobar (CTA)
  README.md
  infobar-cta/client.js
  infobar-cta/config.png
  infobar-cta/evergage-template.json
  infobar-cta/template.css
  infobar-cta/template.hbs
  infobar-cta/template.png
  infobar-cta/template.ts
Labels: Release Requested, Security
